# Generated by Django 3.0.6 on 2021-06-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0002_auto_20210610_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setuptype',
            name='setup_type',
        ),
        migrations.AddField(
            model_name='setuptype',
            name='name',
            field=models.CharField(default='NA', max_length=125, verbose_name='Name'),
        ),
    ]
