# Generated by Django 3.0.6 on 2021-06-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=125, verbose_name='Name')),
                ('db', models.CharField(default='NA', max_length=125, verbose_name='DB')),
                ('connector1', models.CharField(default='NA', max_length=125, verbose_name='Connector1')),
                ('connector2', models.CharField(default='NA', max_length=125, verbose_name='Connector2')),
                ('watt', models.CharField(default='NA', max_length=125, verbose_name='Watt')),
                ('length', models.CharField(default='NA', max_length=125, verbose_name='Length')),
                ('quantity', models.CharField(default='NA', max_length=125, verbose_name='Quantity')),
                ('remark', models.CharField(default='NA', max_length=125, verbose_name='Remark')),
            ],
            options={
                'db_table': 'consumables',
            },
        ),
        migrations.CreateModel(
            name='SetupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=125, verbose_name='Name')),
                ('remark', models.CharField(default='NA', max_length=125, verbose_name='Remark')),
            ],
            options={
                'db_table': 'setup_types',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=125, verbose_name='Name')),
                ('manager', models.CharField(default='NA', max_length=125, verbose_name='Manager')),
                ('remark', models.CharField(default='NA', max_length=125, verbose_name='Remark')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Name')),
                ('email', models.CharField(max_length=125, verbose_name='Email')),
                ('address', models.CharField(max_length=125, verbose_name='Address')),
                ('number', models.CharField(max_length=125, verbose_name='Number')),
                ('remark', models.CharField(max_length=125, verbose_name='Remark')),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=125, verbose_name='Name')),
                ('bookable', models.BooleanField(default=False)),
                ('remark', models.CharField(default='NA', max_length=125, verbose_name='Remark')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setups', to='ReservationTool.Team')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setups', to='ReservationTool.Consumable')),
                ('setup_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setups', to='ReservationTool.SetupType')),
            ],
            options={
                'db_table': 'setups',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=125, verbose_name='Name')),
                ('make', models.CharField(default='NA', max_length=125, verbose_name='Make')),
                ('model', models.CharField(default='NA', max_length=125, verbose_name='Model')),
                ('part_no', models.CharField(default='NA', max_length=125, verbose_name='Part No.')),
                ('remark', models.CharField(default='NA', max_length=125, verbose_name='Remark')),
                ('setup', models.ManyToManyField(blank=True, related_name='device_types', to='ReservationTool.Setup')),
            ],
            options={
                'db_table': 'device_types',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=125, verbose_name='Name')),
                ('srno', models.CharField(default='NA', max_length=125, verbose_name='Serial No.')),
                ('po_number', models.CharField(default='NA', max_length=125, verbose_name='PO No.')),
                ('po_date', models.DateField()),
                ('invoice_number', models.CharField(default='NA', max_length=125, verbose_name='Invoice No.')),
                ('bonded', models.BooleanField(default=False)),
                ('bond_number', models.CharField(default='NA', max_length=125, verbose_name='Bond No.')),
                ('shipped_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('warranty_inmonths', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36)], verbose_name='Warranty(In months)')),
                ('added_byuser', models.CharField(default='NA', max_length=125, verbose_name='Added by user')),
                ('added_date', models.DateField()),
                ('ownership', models.CharField(choices=[('t1', 'Type 1'), ('t2', 'Type 2'), ('t3', 'Type 3')], default='t1', max_length=2, verbose_name='Ownership')),
                ('remark', models.CharField(default='NA', max_length=125, verbose_name='Remark')),
                ('setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='ReservationTool.Setup')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='ReservationTool.DeviceType')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='ReservationTool.Vendor')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
    ]
