# Generated by Django 3.1.7 on 2021-04-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0002_auto_20210424_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='attenuator',
            field=models.IntegerField(default='10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setup',
            name='attenuator_db',
            field=models.CharField(default='10db', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setup',
            name='rf_cable',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setup',
            name='rf_shield_box',
            field=models.IntegerField(default='5'),
            preserve_default=False,
        ),
    ]
