# Generated by Django 3.1.7 on 2021-04-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0003_auto_20210425_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='attenuator',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='attenuator_db',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='rf_cable',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='rf_shield_box',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='setup_type',
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterModelTable(
            name='device',
            table='devices',
        ),
        migrations.AlterModelTable(
            name='setup',
            table='setups',
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
        migrations.DeleteModel(
            name='SetupType',
        ),
    ]
