# Generated by Django 3.1.7 on 2021-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0004_auto_20210426_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='attenuator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setup',
            name='attenuator_db',
            field=models.CharField(default='10db', max_length=125),
        ),
        migrations.AddField(
            model_name='setup',
            name='rf_cable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setup',
            name='rf_shield_box',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setup',
            name='setup_name',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
