# Generated by Django 3.0.6 on 2021-06-10 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
