# Generated by Django 3.0.6 on 2021-06-10 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReservationTool', '0006_auto_20210610_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='added_on',
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Booking', to=settings.AUTH_USER_MODEL),
        ),
    ]
