# Generated by Django 3.1.7 on 2021-05-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0009_auto_20210504_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='consumable_connector1',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='consumable_connector2',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='consumable_db',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='consumable_length',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='consumable_name',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='consumable_quantity',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='consumable_remark',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='consumable_watt',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='createsetup',
            name='create_setup_name',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='createsetup',
            name='create_setup_remark',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_added_byuser',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_added_date',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_bond_number',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_bonded',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_invoice_number',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_ownership',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_po_number',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_remark',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_srno',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_vendor',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_warranty_inmonths',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='type_make',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='type_model',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='type_name',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='type_part_no',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='type_remark',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_address',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_email',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_number',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_remark',
            field=models.CharField(default='NA', max_length=125),
        ),
    ]
