# Generated by Django 3.1.7 on 2021-05-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0010_auto_20210504_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(default='NA', max_length=125),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_address',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_email',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_number',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_remark',
            field=models.CharField(max_length=125),
        ),
        migrations.CreateModel(
            name='MakeSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_setup_consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ReservationTool.consumable')),
                ('make_setup_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ReservationTool.device')),
                ('make_setup_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ReservationTool.createsetup')),
            ],
            options={
                'db_table': 'make_setup',
            },
        ),
    ]
