# Generated by Django 3.1.7 on 2021-05-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0012_auto_20210507_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='id',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='type_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
