# Generated by Django 3.1.7 on 2021-05-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0014_auto_20210507_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makesetup',
            old_name='make_setup_consumable',
            new_name='consumable_name',
        ),
    ]
