# Generated by Django 3.1.7 on 2021-05-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0015_auto_20210510_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makesetup',
            old_name='consumable_name',
            new_name='make_setup_consumable',
        ),
    ]
