# Generated by Django 3.1.7 on 2021-05-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0023_remove_device_warranty_inmonths'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='warranty_inmonths',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36)], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='ownership',
            field=models.CharField(choices=[('t1', 'Type 1'), ('t2', 'Type 2'), ('t3', 'Type 3')], default='t1', max_length=2),
        ),
    ]
