# Generated by Django 3.0.6 on 2021-05-29 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0025_auto_20210529_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='setup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='ReservationTool.Setup'),
            preserve_default=False,
        ),
    ]
