# Generated by Django 3.0.6 on 2021-05-29 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0026_auto_20210529_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='ReservationTool.Setup'),
        ),
    ]
