# Generated by Django 3.0.6 on 2021-05-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0027_auto_20210529_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='type',
            new_name='device_type',
        ),
    ]
