# Generated by Django 3.0.6 on 2021-06-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0028_auto_20210530_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='device_type',
        ),
    ]
