# Generated by Django 3.0.6 on 2021-06-06 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0029_remove_setup_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setups', to='ReservationTool.Team'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setups', to='ReservationTool.Consumable'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='setup_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setups', to='ReservationTool.SetupType'),
        ),
    ]
