# Generated by Django 3.0.6 on 2021-06-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0030_auto_20210606_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device_types', to='ReservationTool.Setup'),
        ),
    ]
