# Generated by Django 3.0.6 on 2021-06-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0031_devicetype_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='setup',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='setup',
            field=models.ManyToManyField(blank=True, null=True, related_name='device_types', to='ReservationTool.Setup'),
        ),
    ]
