# Generated by Django 3.0.6 on 2021-06-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0032_auto_20210609_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='setup',
            field=models.ManyToManyField(blank=True, related_name='device_types', to='ReservationTool.Setup'),
        ),
    ]
