# Generated by Django 3.1.7 on 2021-06-10 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReservationTool', '0033_auto_20210609_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('setup', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Booking', to='ReservationTool.setup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
