# Generated by Django 3.1.7 on 2021-06-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0034_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
    ]
