# Generated by Django 3.1.7 on 2021-04-23 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=125)),
                ('serial_number', models.CharField(max_length=125)),
                ('ip', models.CharField(max_length=125)),
                ('mac', models.CharField(max_length=125)),
                ('device_type', models.CharField(max_length=125)),
                ('make', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_name', models.CharField(max_length=125)),
                ('setup_type', models.CharField(max_length=125)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationTool.device')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationTool.setup')),
            ],
        ),
    ]
