# Generated by Django 3.1.7 on 2021-04-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='server_id',
        ),
        migrations.RemoveField(
            model_name='servertype',
            name='server_type_id',
        ),
        migrations.AddField(
            model_name='server',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servertype',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
