# Generated by Django 3.1.7 on 2021-04-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0002_auto_20210501_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_added_ondate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_po_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_ship_date',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='server',
            table=None,
        ),
        migrations.AlterModelTable(
            name='servertype',
            table=None,
        ),
    ]
