# Generated by Django 3.1.7 on 2021-04-30 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0003_auto_20210501_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='RrhType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrh_type_name', models.CharField(default='NA', max_length=125)),
                ('rrh_part_number', models.CharField(default='NA', max_length=125)),
                ('rrh_model_number', models.CharField(default='NA', max_length=125)),
                ('rrh_band', models.CharField(default='NA', max_length=125)),
                ('rrh_remark', models.CharField(default='NA', max_length=125)),
            ],
            options={
                'db_table': 'rrh_type',
            },
        ),
        migrations.AlterModelTable(
            name='server',
            table='add_server',
        ),
        migrations.AlterModelTable(
            name='servertype',
            table='server_type',
        ),
        migrations.CreateModel(
            name='RRH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrh_name', models.CharField(default='NA', max_length=125)),
                ('rrh_serial_number', models.CharField(default='NA', max_length=125)),
                ('rrh_po_number', models.CharField(default='NA', max_length=125)),
                ('rrh_po_date', models.DateField()),
                ('rrh_vendor', models.CharField(default='NA', max_length=125)),
                ('rrh_invoice', models.CharField(default='NA', max_length=125)),
                ('rrh_hdd_number', models.CharField(default='NA', max_length=125)),
                ('rrh_bond', models.CharField(default='NA', max_length=125)),
                ('rrh_bond_number', models.CharField(default='NA', max_length=125)),
                ('rrh_oftype', models.CharField(default='NA', max_length=125)),
                ('rrh_ship_date', models.DateField()),
                ('rrh_arrival_date', models.DateField()),
                ('rrh_warranty', models.CharField(default='NA', max_length=125)),
                ('rrh_added_byuser', models.CharField(default='NA', max_length=125)),
                ('rrh_added_ondate', models.DateField()),
                ('rrh_ownership', models.CharField(default='NA', max_length=125)),
                ('rrh_ip_address', models.CharField(default='NA', max_length=125)),
                ('rrh_hostname', models.CharField(default='NA', max_length=125)),
                ('rrh_mgmt_mac', models.CharField(default='NA', max_length=125)),
                ('rrh_lan_mac', models.CharField(default='NA', max_length=125)),
                ('rrh_os', models.CharField(default='NA', max_length=125)),
                ('rrh_fversion', models.CharField(default='NA', max_length=125)),
                ('rrh_hardware_revision', models.CharField(default='NA', max_length=125)),
                ('rrh_setup_id', models.CharField(default='NA', max_length=125)),
                ('rrh_remark', models.CharField(default='NA', max_length=125)),
                ('rrh_type_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ReservationTool.rrhtype')),
            ],
            options={
                'db_table': 'add_rrh',
            },
        ),
    ]
