# Generated by Django 3.1.7 on 2021-04-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0006_auto_20210426_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='attenuator',
            new_name='attenuator_quantity',
        ),
    ]
