# Generated by Django 3.1.7 on 2021-05-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0007_auto_20210427_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumable_name', models.CharField(max_length=125)),
                ('consumable_db', models.CharField(max_length=125)),
                ('consumable_connector1', models.CharField(max_length=125)),
                ('consumable_connector2', models.CharField(max_length=125)),
                ('consumable_watt', models.CharField(max_length=125)),
                ('consumable_length', models.CharField(max_length=125)),
                ('consumable_quantity', models.CharField(max_length=125)),
                ('consumable_remark', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'consumables',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=125)),
                ('type_make', models.CharField(max_length=125)),
                ('type_model', models.CharField(max_length=125)),
                ('type_part_no', models.CharField(max_length=125)),
                ('type_remark', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'device_types',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=125)),
                ('vendor_email', models.CharField(max_length=125)),
                ('vendor_address', models.CharField(max_length=125)),
                ('vendor_number', models.CharField(max_length=125)),
                ('vendor_remark', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_type',
            new_name='device_added_byuser',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='hostname',
            new_name='device_added_date',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='ip',
            new_name='device_arrival_date',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='mac',
            new_name='device_bond_number',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='make',
            new_name='device_bonded',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='serial_number',
            new_name='device_invoice_number',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='setup_type',
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='NA', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_ownership',
            field=models.CharField(default='NA', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_po_date',
            field=models.CharField(default='NA', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_po_number',
            field=models.CharField(default='NA', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_remark',
            field=models.CharField(default='NA', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_shipped_date',
            field=models.CharField(default='NA', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_srno',
            field=models.CharField(default='NA', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_vendor',
            field=models.CharField(default='NA', max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_warranty_inmonths',
            field=models.CharField(default='NA', max_length=125),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SetupType',
        ),
    ]
