# Generated by Django 3.1.7 on 2021-05-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0013_auto_20210507_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='createsetup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.RemoveField(
            model_name='makesetup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='id',
        ),
        migrations.AddField(
            model_name='consumable',
            name='consumable_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createsetup',
            name='create_setup_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makesetup',
            name='make_setup_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='type_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
