# Generated by Django 3.1.7 on 2021-05-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0021_auto_20210528_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='bonded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='warranty_inmonths',
            field=models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')]),
        ),
    ]
