# Generated by Django 3.1.7 on 2021-05-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0022_auto_20210528_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='warranty_inmonths',
        ),
    ]
