# Generated by Django 3.1.7 on 2021-06-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationTool', '0024_auto_20210528_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makesetup',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='make_setup', to='ReservationTool.device'),
        ),
    ]
